// Helper to load optimized srcsets from manifest generated by scripts/optimize-images.mjs
export type SrcSetEntry = { src: string; w: number };
export type OptimizedEntry = { webp: SrcSetEntry[]; avif: SrcSetEntry[] };
export type ImagesManifest = Record<string, OptimizedEntry>;

let manifest: ImagesManifest | null = null;

export async function loadImagesManifest(): Promise<ImagesManifest | null> {
  if (manifest) return manifest;
  try {
    const res = await fetch('/optimized/images-manifest.json', { cache: 'no-store' });
    if (!res.ok) return null;
    manifest = await res.json();
    return manifest;
  } catch {
    return null;
  }
}

export function toSrcSet(entries: SrcSetEntry[] = []): string {
  return entries.map(e => `${e.src} ${e.w}w`).join(', ');
}
